export enum MapChipType {
  BuanMarketColor = 'BuanMarketColor',
  BuanMarketWhite = 'BuanMarketWhite',
  ElectronicChargeColor = 'ElectronicChargeColor',
  ElectronicChargeWhite = 'ElectronicChargeWhite',
  ParkingColor = 'ParkingColor',
  ParkingWhite = 'ParkingWhite',
  RedStreetColor = 'RedStreetColor',
  RedStreetWhite = 'RedStreetWhite',
  SentimentalStreetColor = 'SentimentalStreetColor',
  SentimentalStreetWhite = 'SentimentalStreetWhite',
  ShelterColor = 'ShelterColor',
  ShelterWhite = 'ShelterWhite',
  ToiletColor = 'ToiletColor',
  ToiletWhite = 'ToiletWhite',
  WholeColor = 'WholeColor',
  WholeWhite = 'WholeWhite',
  YouthStreetColor = 'YouthStreetColor',
  YouthStreetWhite = 'YouthStreetWhite'
}
